remote_theme: kitian616/jekyll-text-theme

## Site Settings
title: "Tech Blog"
description: "Tech Blog"
url: "https://seojunhaha.github.io"
baseurl: "/blog"
repository: "seojunhaha/blog"

## Language and Timezone
lang: ko
timezone: Asia/Seoul

## Author
author:
  type: person
  name: "seojunhaha"
  url: "https://github.com/seojunhaha"

## Markdown and Syntax Highlighting
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

## Paginate
paginate: 10
paginate_path: /page:num/

## Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

## Paths
paths:
  root: /blog

## Navigation (상단)
header:
  title: "Tech Blog"

## TOC
toc:
  selectors: "h1,h2,h3"

## Sidebar Navigation (왼쪽 사이드바)
sidebar:
  nav: docs

## Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sidebar:
        nav: docs
      aside:
        toc: true
      show_edit_on_github: false
      show_subscribe: false
      license: false
  - scope:
      path: ""
    values:
      layout: article
      sidebar:
        nav: docs
      aside:
        toc: true
