remote_theme: kitian616/jekyll-text-theme
text_skin: default
highlight_theme: default

## Site Settings
title: "Computer Vision Research Space"
description: "Learning to See"
url: "https://seojunhaha.github.io"
baseurl: "/blog"
repository: "seojunhaha/blog"

## Language and Timezone
lang: ko
timezone: Asia/Seoul

## Author
author:
  type: person
  name: "seojunhaha"
  url: "https://github.com/seojunhaha"

## Markdown and Syntax Highlighting
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

## Paginate
paginate: 10
paginate_path: /page:num/

## Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

## Paths
paths:
  root: /

## TOC
toc:
  selectors: "h1,h2,h3"

## Sidebar
sidebar:
  nav: docs

## Footer (팔로우 섹션 숨김)
footer:
  powered_by: false
  hosted_on: false

## Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sidebar:
        nav: docs
      aside:
        toc: true
      show_edit_on_github: false
      show_subscribe: false
      show_tags: true
      show_date: true
      license: false
      sharing: false
  - scope:
      path: ""
    values:
      layout: article
      sidebar:
        nav: docs
      aside:
        toc: true
      show_subscribe: false
      license: false
      sharing: false
